/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5b1a7e84-60c0-4173-bceb-d52be363f6c4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_o4pMbY069",
    "aws_user_pools_web_client_id": "5871b0gk2p070e8s8lsa5sb525",
    "oauth": {}
};


export default awsmobile;
